### ISSUE TITLE
sub module for php

### ISSUE THREAD

**Issue by wookiecooking** [baconface/php-webkit#2]
Instead of maintaining binaries for php in the repo, why not create a submodule in git to pull the php repo.

**Comment by baconbrad** [comment]
You're right. It was initially put in to make this repo a complete proof of concept. Tonight I will make instructions on how to properly package PHP binaries within the NW.js project and put those in the README.md in that directory. I will then delete the files in that directory except for the README.md.

**Comment by wookiecooking** [comment]
The one issue Im worried about is being cross-platform. I'm not a windows/mac user, so I would gladly beable to partake in trying to get a linux version going, but I believe we would have to pass around a binary for it, or maybe we can use node-gyp.

**Comment by baconbrad** [comment]
I have Ubuntu Linux as well as Windows 8.1 so I agree. I designed it where you can package PHP within your project but it still supports the shell call to cgi-php if you wished to use a repo version of PHP. Out of the box the Windows versions of PHP work by dropping them in the directory. Linux and Mac are trickier since repos and building from source put them in multiple directories. I was able to modify the packaged Linux binaries for [PHP Nightrain](https://github.com/naetech/nightrain) and get it to work in Ubuntu and Windows without changes to the php-webkit source code. I don't have a Mac to test those on. So php-webkit should be cross platform in its current state. Just packaging the PHP binaries on a UNIX machine is a lot harder than using repos or building from source. Users on those machines will likely opt to override bin in the package.json. I would like to look into automating this task for builds.

**Comment by wookiecooking** [comment]
:+1: Agreed, great work on the Nighttrain hack, didn't even consider that.
Automating builds could be done, maybe create a custom buildpack for heroku
that can compile and serve the binaries?

I have another project for nw.js that compiles projects with grunt, was in
the process of rewriting it for this project so it can be automated on the
conversion, which also downloads binaries from locations for nw.js.

**Comment by baconbrad** [comment]
I have used [node-webkit-builder](https://www.npmjs.com/package/node-webkit-builder) for my builds. But I am aware of the [grunt builder for NPM](https://www.npmjs.com/package/grunt-node-webkit-builder) you mentioned. I was thinking making a build setup that packages your target machines PHP binaries into the php folder and use the NW.js packaging NPM to create the final product. From there we would have a full solution for command line developers. I imagine we could also make a GUI interface for this as well that does the command line build behind the scenes. It would then boil down to coming up with a noninvasive standard way to make UNIX PHP packages based off of the PHP releases. This at least was my ultimate goal.

**Comment by baconbrad** [comment]
Original issue at hand resolved with 7e9a18b645ce9facadc3c7f294fbc18b4a62ed32

**Comment by wookiecooking** [comment]
:+1:
