### ISSUE TITLE
npm Warn Error about package.json

### ISSUE THREAD

**Issue by 2braincells2go** [baconface/php-webkit#22]
Nice project, thanks for sharing with the community!

Not positive this is really an issue but having some problems and wanted to make sure.

When running "install npm" in project directory, get a warning:

"npm WARN package.json php-webkit@0.0.1 No repository field."

Is this a warning I should be concerned with or just an alert?

Thanks for your time.

**Comment by baconbrad** [comment]
Nothing to be concerned with. NPM puts warnings if things like a repo and a read me are not available because they are needed for the package page. PHP-Webkit has a package.json to load dependencies, set configuration, and for NW.js but is not in itself an NPM package. I haven't had time to maintain this project. But I update it with a repo when I get a chance. Until then there is no harm.

**Comment by 2braincells2go** [comment]
Good deal, thank much.
